name: GA Build CI Pipeline
on:
  push:
    branches: 
      - main
env:
  DAY_OF_WEEK: monday  # Global environment variable
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm start
      
    - name: Run tests
      run: npm test
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      First_Name: Mona
    steps:
    - name: "Say Hello Mona it's Monday"
      if: ${{ env.DAY_OF_WEEK == 'monday' }}
      run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
